### PR TITLE
Update swagger-ui to 2.1.1-M1

### PR DESCRIPTION
**Pull request by mattcarrier**
Update from 1.3.2 to 2.1.1-M1 of swagger-ui.

### CODE REVIEW

**Comment by federecio** [comment]
thank you very much Matt. I will take a look

**Comment by mattcarrier** [comment]
Sorry about the last commit (the updated version number). It looks like that made it into the pull request auto-magically. If it's a problem let me know and I can give you a new pull request.

**Comment by mattcarrier** [comment]
Nevermind, just removed the last commit.

**Comment by federecio** [comment]
Deployed a new snapshot 0.5.3-SNAPSHOT with the latest changes. If you can give it a try please let me know.

**Comment by mattcarrier** [comment]
Will do, I'll let you know.

**Comment by mattcarrier** [comment]
working for me, thanks!

**Pull request merged**
