### PR TITLE
make Swagger more dropwizard friendly

### PR DESCRIPTION
**Pull request by tburch**
I refactored things a little to make this a little more Dropwizard friendly in terms of instantiating the bundle.

### CODE REVIEW

**Comment by federecio** [comment]
Thank you very much for the pull request, it looks neat. You found a nice way to use the Configuration object to set up the bundle (considering that the Configuration object is not available until the run() method is called).

It now seems odd to have SwaggerBundle and SwaggerDropwizard classes: they should be merged into one and the old onInitialize() and onRun() methods have to deprecated and then removed.

I will deploy a new snapshot soon and will let you know.

**Comment by tburch** [comment]
Yeah, I wasn't sure about removing them, so I just left them there for now.

**Comment by federecio** [comment]
Deployed a new snapshot 0.5.3-SNAPSHOT, if you could give it a try let me know and I'll release it under version 0.5.3

**Comment by tburch** [comment]
Looks like my changes are working, but the Swagger UI isn't loading (looks
like it's missing /lib/swagger-oauth.js).

**Comment by federecio** [comment]
@mattcarrier do you know about this?

**Comment by mcarrierastonish** [comment]
@tburch @federecio Yeah, I missed that import in the freemarker view, I'll send in a pull request shortly. I don't think that is the main issue causing the UI not to load though. You can see the latest snapshot working here:
http://squaresfree.com/swagger.  You will also see the same console error there loading the oauth lib and the UI loads just fine.  Are you utilizing there oauth features?

**Comment by tburch** [comment]
I'm not utilizing any oauth features... just the basic swagger stuff.

**Comment by mcarrierastonish** [comment]
@tburch
https://github.com/federecio/dropwizard-swagger/pull/34

This will at least alleviate the console log so you can rule that out.

**Comment by federecio** [comment]
I pushed a new snapshot with the latest pull request. 

@tburch could try again? make sure you add -U to the mvn command to force to update snapshots. If it still doesn't work, you'll need to share more information on your project so that I can try to determine what the problem is.

**Comment by tburch** [comment]
It's working now, but still 404'ing on the js file (
http://localhost:8080/lib/swagger-oauth.js). I was testing this out in a
new project and forgot the @Api annotation on the class.

**Comment by federecio** [comment]
that is weird, I'm trying the sample app -> https://github.com/federecio/dropwizard-swagger-sample-app

and I'm not getting 404s for swagger-oauth.js

If your application context path is different than / (root) I suspect the problem is you are using an old snapshot (one that does not contain @mattcarrier latest changes). Unless you share your project, it's hard to diagnose further.

**Comment by tburch** [comment]
Yeah, you're right. Our nexus installation didn't seem to be wanting to
pull the newest snapshot. After manually removing the version, it'd not
404'ing anymore. Sorry for the trouble!

**Comment by mcarrierastonish** [comment]
@tburch glad to hear thanks for finding that invalid import!

**Comment by federecio** [comment]
thank you guys, I released a new version 0.5.3:

https://oss.sonatype.org/content/repositories/releases/io/federecio/dropwizard-swagger/0.5.3/

You should update your projects to point to this new version

**Pull request merged**
