### PR TITLE
Add support for Dropwizard v0.8.0

### PR DESCRIPTION
**Pull request by vultron81**

### CODE REVIEW

**Comment by vamsi-subhash** [comment]
Can this be merged? The current version doesn't support 0.8.0

**Comment by federecio** [comment]
@vultron81 Thank you very much for taking the time to put this together. I apologize for my delayed response but I'm currently enjoying some time off. I did want to take a quick look at your PR but after checking out the code all of the Selenium tests are failing for me. Do you get a clean run after `mvn clean install` ?

**Comment by clamothe** [comment]
Works for me.

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by clamothe** [comment]
Works for me.

git checkout v0.8.0-support
mvn clean test
...
Results :

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by federecio** [comment]
@vultron81 Thank you very much for sending this PR. Adding support for DW 0.8 is definitely very important. I merged another pending PR adding support for DW 0.8 plus I added some changes myself.

@vamsi-subhash I deployed a snapshot with version 0.6-SNAPSHOT to first test the changes and if everything works ok I will deploy a release. If you guys would like to give a try it would be awesome.  To use the snapshot you'd need to temporarily add a snapshot repository with the following URL:

             <url>https://oss.sonatype.org/content/repositories/snapshots</url>

@clamothe my bad, I had my network configuration all messed up and that was why tests were failing for me.

**Pull request closed without merging**
